name: Build and Deploy Magic Land React Application https://vote.minmax.finance/

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build2
        
      - name: List output files
        run: find out/ -print
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.prod_ftp_server }}
          username: ${{ secrets.prod_ftp_username }}
          password: ${{ secrets.prod_ftp_password }}
          protocol: ftps
          local-dir: out/
          port: 21
